
@startuml architecture
title Project Architecture
skinparam useBetaStyle true

<style>
    .package {
        BackgroundColor Khaki
    }
</style>

skinparam component {
  ArrowColor #FF6655
}

node spring {
    component [boot] as boot {
        package autoconfigure
    }
    component [context] as ctx
    component [web] as web
    component [beans] as beans
    component [core] as c2

}

component [javafx] {
    component [fxml] as fx
}

node "eventplanner" as ep {
    component [core] {
        package eventplanner.core
        package eventplanner.json
    }

    component [fxui] {
        package eventplanner.dataaccess
        package eventplanner.fxui
    }

    component [rest] {
        package eventplanner.rest

    }
}


component [java.net] {
    component [http] as net
}

component [jackson] as jack

eventplanner.dataaccess ..> fx
fxui ..> core
eventplanner.dataaccess .right.> net
eventplanner.json .left.> jack
rest .left.> jack
rest .left.> spring
rest ..> eventplanner.core
rest ..> eventplanner.json

@enduml
