@startuml Sequence Diagram - Register user and register events
title Sequence Diagram 

skinparam SequenceMessageAlignment center
participant "Frontend App" order 1
participant "API level" order 2
participant "Server/Model" order 3

"Frontend App" -> "API level" : User click "Register user" \n-email: String\n-password: String\n-above18: boolean

note left 
    **__Start info:__**
    User Registeres and
    registeres on an event
    through event's info
    page. User also creates
    an event and then 
    deletes it at the end
end note 

"API level" -> "Server/Model" : createUser(User user)
"Server/Model" -> "Server/Model" : validation

note right 
    Validation of all
    passed parameters
    in **Validation.java**
    class to create user
end note

alt Success
"API level" <-- "Server/Model" : Success
"Frontend App" <-- "API level" : Success
else Error
"API level" <-- "Server/Model" : Error\n-Email is invalid\n-Password is invalid\n-Date is not set\n-User already exists or invalid input
"Frontend App" <-- "API level" : Error\n-Date is not set\n-User already exists or invalid input
end

"API level" -> "Server/Model" : getAllEvents()
"Server/Model" -> "Server/Model" : instanciate event\nobjects

note right 
    After user is created
    default events are 
    instanciated in order
    to be displayed on 
    main page **AllEvents**
end note

"API level" <-- "Server/Model" : Success
"Frontend App" <-- "API level" : Success: view AllEventsPage
"Frontend App" -> "API level" : User click "Read more" on EventCell
"API level" -> "Server/Model" : updateItem(event,boolean)
"API level" <-- "Server/Model" : Success
"Frontend App" <-- "API level" : Success: view EventPage
"Frontend App" -> "API level" : User click on "Register"
"API level" -> "Server/Model" : handleRegisterEventBtnClicked()

alt Success
"API level" <-- "Server/Model" : Success\n-You have successfully\nregistered to event
"Frontend App" <-- "API level" : Success\n-You have successfully\nregistered to event
else Error
"API level" <-- "Server/Model" : Error\n-An error occured while\ntrying to register user
"Frontend App" <-- "API level" : Error\n-An error occured while\ntrying to register user
end

"Frontend App" -> "API level" : User click "Create new event"\n-eventType: EventType\n-name: String\n-localDateTimeStart: LocalDateTime\n-localDateTimeEnd: LocalDateTime\n-location: String\n-description: String
"API level" -> "Server/Model" : createEvent(Event event)
"Server/Model" -> "Server/Model" : validation

note right 
    Validation of all
    passed parameters
    in **Validation.java**
    class to create event 
end note

alt Success
"API level" <-- "Server/Model" : Success
"Frontend App" <-- "API level" : Success
else Error
"API level" <-- "Server/Model" : Error\n-Something went wrong while saving\nCan't add event to file
"Frontend App" <-- "API level" : Error\n-Something went wrong while saving\nCan't add event to file
end

"Frontend App" -> "API level" : User click on "Delete event"
"API level" -> "Server/Model" : deleteEvent(Event event)
@enduml